const styles = {
  content: {
    width: '480px',
    margin: '50px'
  },
  h3: {
    fontFamily: 'Lato',
    fontWeight: '300',
    fontSize: '15px',
    color: '#4f4f4f',
    marginLeft: '40px'
  },
  editor: {
    border: 'solid',
    color: 'red',
    margin: '60px',
    background: 'red'
  },
  button: {
    color: 'red',
  },
  strikethrough: {
    textDecoration: 'line-through'
  },
  title: {
    fontFamily: 'Alegreya',
    fontSize: '30px',
    color: '#4f4f4f',
    marginLeft: '30px'
  },
  toolbar: {
    marginLeft: '30px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: '30px',
    borderRadius: '2px',
    backgroundColor: '#f2f1ed',
    height: '60px',
    width: '850px',
    boxShadow: 'inset 0 0 7px rgba(0, 0, 0, 0.05)'
  },
  buttonflat: {
    active: {
      top: '1px',
      outline: 'none',
      boxShadow: 'none',
    },
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '25px',
    height: '25px',
    borderRadius: '3px',
    padding: '2',
    fontSize: '15px',
    color: 'white',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#f1c40f',
    border: '0',
    borderBottom: '2px solid #e2b607',
    boxShadow: 'inset 0 -2px #e2b607',
  },
  buttonflatGR: {
    fontFamily: 'Garamond',
    active: {
      top: '1px',
      outline: 'none',
      boxShadow: 'none',
    },
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '25px',
    height: '25px',
    borderRadius: '3px',
    padding: '2',
    fontSize: '15px',
    color: 'white',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#9CCC65',
    border: '0',
    borderBottom: '2px solid #7CB342',
    boxShadow: 'inset 0 -2px #7CB342',
  },
  fontRed: {
    color: '#c62828'
  },
  fontBlue: {
    color: '#2196F3'
  },
  fontGray: {
    color: '#4f4f4f'
  },
  buttonflatR: {
    active: {
      top: '1px',
      outline: 'none',
      boxShadow: 'none',
    },
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '25px',
    height: '25px',
    borderRadius: '3px',
    padding: '2',
    fontSize: '15px',
    color: 'white',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#e53935',
    border: '0',
    borderBottom: '2px solid #c62828',
    boxShadow: 'inset 0 -2px #c62828',
  },
  buttonflatG: {
    active: {
      top: '1px',
      outline: 'none',
      boxShadow: 'none',
    },
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '25px',
    height: '25px',
    borderRadius: '3px',
    padding: '2',
    fontSize: '15px',
    color: 'white',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#4f4f4f',
    border: '0',
    borderBottom: '2px solid #383838',
    boxShadow: 'inset 0 -2px #383838',
  },
  buttonflatB: {
    active: {
      top: '1px',
      outline: 'none',
      boxShadow: 'none',
    },
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '25px',
    height: '25px',
    borderRadius: '3px',
    padding: '2',
    fontSize: '15px',
    color: 'white',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#2196F3',
    border: '0',
    borderBottom: '2px solid #1976D2',
    boxShadow: 'inset 0 -2px #1976D2',
  },
  buttonflatP: {
    active: {
      top: '1px',
      outline: 'none',
      boxShadow: 'none',
    },
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '25px',
    height: '25px',
    borderRadius: '3px',
    padding: '2',
    fontSize: '15px',
    color: 'white',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#3F51B5',
    border: '0',
    borderBottom: '2px solid #303F9F',
    boxShadow: 'inset 0 -2px #303F9F',
  },
  allButTitle: {
    display: 'flex',
    flex: '1',
    justifyContent: 'left',
    alignItems: 'center',
  },
  buttonflatT: {
    active: {
      top: '1px',
      outline: 'none',
      boxShadow: 'none',
    },
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '25px',
    height: '25px',
    borderRadius: '3px',
    padding: '2',
    fontSize: '15px',
    color: 'white',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#26A69A',
    border: '0',
    borderBottom: '2px solid #00897B',
    boxShadow: 'inset 0 -2px #00897B',
  },
  buttonLarge: {
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '200px',
    height: '30px',
    borderRadius: '3px',
    padding: '2px',
    fontSize: '18px',
    color: 'white',
    marginLeft: '40px',
    marginTop: '20px',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#c6c6c6',
    border: '0',
    borderBottom: '1px solid #b7b7b7',
    boxShadow: 'inset 0 -2px #b7b7b7',
  },
  buttonSave: {
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '100px',
    height: '30px',
    borderRadius: '3px',
    padding: '2px',
    fontSize: '18px',
    color: 'white',
    marginRight: '40px',
    marginTop: '20px',
    textAlign: 'center',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#D81B60',
    border: '0',
    borderBottom: '1px solid #AD1457',
    boxShadow: 'inset 0 -2px #AD1457',
  },
  buttonRevHist: {
    active: {
      top: '1px',
      outline: 'none',
      boxShadow: 'none',
    },
    position: 'relative',
    margin: '5px',
    verticalAlign: 'top',
    width: '200px',
    height: '25px',
    borderRadius: '3px',
    padding: '2',
    fontSize: '15px',
    color: 'white',
    textAlign: 'center',
    marginLeft: '30px',
    textShadow: '0 1px 2px rgba(0, 0, 0, 0.25)',
    background: '#9C27B0',
    border: '0',
    borderBottom: '2px solid #7B1FA2',
    boxShadow: 'inset 0 -2px #7B1FA2',
  },
};

export default styles;
